import { db } from '@/db';
import { foodItems } from '@/db/schema';

async function main() {
    const sampleFoodItems = [
        // Snacks (8 items)
        {
            name: 'Small Popcorn',
            description: 'Freshly popped buttery popcorn in a small bucket',
            price: 5.99,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Medium Popcorn',
            description: 'Freshly popped buttery popcorn in a medium bucket',
            price: 7.49,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Large Popcorn',
            description: 'Freshly popped buttery popcorn in a large bucket',
            price: 8.99,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Nachos with Cheese',
            description: 'Crispy tortilla chips served with warm nacho cheese sauce',
            price: 6.99,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Hot Dog',
            description: 'Classic all-beef hot dog with choice of toppings',
            price: 5.49,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1612392166886-ee9c70b66c5b',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Soft Pretzel',
            description: 'Warm salted pretzel served with cheese dip',
            price: 4.99,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1558326567-98ae2405596b',
            available: 0,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Candy Assortment',
            description: 'Selection of popular movie theater candies',
            price: 3.99,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Loaded Nachos',
            description: 'Nachos topped with cheese, jalapeños, sour cream, and guacamole',
            price: 9.49,
            category: 'Snack',
            imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        
        // Drinks (7 items)
        {
            name: 'Small Fountain Drink',
            description: 'Choice of Coke, Sprite, Fanta, or other fountain beverages',
            price: 4.49,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Medium Fountain Drink',
            description: 'Choice of Coke, Sprite, Fanta, or other fountain beverages',
            price: 5.49,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Large Fountain Drink',
            description: 'Choice of Coke, Sprite, Fanta, or other fountain beverages',
            price: 6.49,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Bottled Water',
            description: 'Premium bottled spring water',
            price: 3.99,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Fresh Lemonade',
            description: 'Freshly squeezed lemonade served ice cold',
            price: 5.99,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f8d',
            available: 0,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Iced Coffee',
            description: 'Cold brew coffee served over ice with optional flavors',
            price: 5.49,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Fruit Punch',
            description: 'Tropical fruit punch blend',
            price: 4.99,
            category: 'Drink',
            imageUrl: 'https://images.unsplash.com/photo-1546173159-315724a31696',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        
        // Combos (5 items)
        {
            name: 'Classic Combo',
            description: 'Medium popcorn and medium fountain drink',
            price: 11.99,
            category: 'Combo',
            imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Large Combo',
            description: 'Large popcorn and large fountain drink',
            price: 13.99,
            category: 'Combo',
            imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Family Bundle',
            description: 'Two large popcorns, four medium drinks, and candy for four',
            price: 35.99,
            category: 'Combo',
            imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Date Night Special',
            description: 'Large popcorn, two medium drinks, and two candies',
            price: 18.99,
            category: 'Combo',
            imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f',
            available: 0,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Kids Meal Deal',
            description: 'Small popcorn, small drink, and choice of candy',
            price: 9.99,
            category: 'Combo',
            imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f',
            available: 1,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(foodItems).values(sampleFoodItems);
    
    console.log('✅ Food items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});